version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput --clear &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 core.wsgi:application"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - database_volume:/app/db
    env_file:
      - .env
    networks:
      - backend
      - monitoring

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
      - monitoring
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --non-interactive --webroot -w /var/www/certbot --email two-potato@yandex.ru --agree-tos --no-eff-email -d glasshalf.ru
    networks:
      - backend
      - monitoring

volumes:
  static_volume:
  media_volume:
  database_volume:

networks:
  backend: