version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./metrics/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
      - backend
    restart: unless-stopped
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    env_file:
      - ./.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./metrics/loki/config.yaml:/etc/loki/config.yaml
    networks:
      - monitoring
      - backend
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
      - ./metrics/promtail/config.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitoring
      - backend
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    name: monitoring
    driver: bridge
  backend:
    external: true